### ISSUE TITLE
Download Stuck at 99.66% in version 0.0.16

### ISSUE THREAD

**Issue by Ares9323** [master-technology/AssetManagerStudio#13]
I tried to download 3 times the new Cropout Sample and it remains stuck at 99.66% forever:
![image](https://github.com/master-technology/AssetManagerStudio/assets/46932745/fca0446b-efc5-44a3-b7fe-b01a3330687a)

Is it possible to see a list of downloads in progress? I tried clicking "Cancel Downloads" but nothing happens, I had to close it manually.

**Comment by NathanaelA** [comment]
Thanks for the report, I'll test downloading this project, interestingly enough it is actually saying it downloaded 529 out of 527 files, so obviously something is wrong as it has downloaded more files that it thinks exists...

**Comment by NathanaelA** [comment]
I haven't been able to duplicate the issue, even though I tried this specific asset.   I have the same type of report from someone else, so I know it is definitely a bug -- still testing, might be a Windows specific bug so that is my next test.      

`Cancel` will only cancel after the file(s) that are in the process of downloading finishes downloading, so if it is downloading a large file, it can appear to take a bit of time to cancel.   This is something I want to rework and actually "Abort" all the current downloads going on, but right now it lets any existing file transfers finish and then stops any future files from this asset.

**Comment by NathanaelA** [comment]
The download system has been revamped in the next version (0.0.17) and I believe will fix this set of issues.   
1. Now using file size, rather than file count.  This is a lot more accurate in how long this will take as larger files tend to be later in the download manifest.
2. A new unified download system.
3. `Cancel` will cancel immediately (i.e.. abort the download).
4. UI should be more accurate on what is going on.
5. List of what is downloading will show up in a later version, debating how I want to display it and where...  :)
