### ISSUE TITLE
[Feature request] Multiple Accounts 

### ISSUE THREAD

**Issue by hiccup0526** [master-technology/AssetManagerStudio#19]

**Comment by NathanaelA** [comment]
Is there a good reason to add code to support logout?

**Comment by hiccup0526** [comment]
I need logout feature to switch accounts.
If there isn't a reason to add logout feature, please tell me how I can logout my current account.
Thanks for your reaponse.

**Comment by NathanaelA** [comment]
Ah, switching accounts -- now that makes a bit more sense.

**Comment by hiccup0526** [comment]
In current state, is there any way to switch account?
I think that is possible if I can delete account info storage.

**Comment by NathanaelA** [comment]
Yes, you can actually do it a couple ways, but all of them are not very "nice".     
1. Depending on if you are on windows or linux, you can delete the actual database and cached files.  Basically a total reset.    On windows, I think it is in your ~AppData/local/asset-manager-studio`, on linux it is in `~/.config/asset-manager-studio`   Nuke that folder and it will restart totally clean.
2. There is a CLI command that will delete the current database `--DELETEDB`, however it is possible that your session will be still valid because of the cached html/cookies from the browser instance.    
3. You can use the CLI command line "SET COOKIES" and "SET OAUTH" to clear your current data, again there is a possibility like 2, where the cached html/cookies from the browser instance will repopulate it.

---

1. Out of curiosity, in a multi-user account setup, would you prefer each user to have their own Asset / Vault list so it is completely separate.     
2.  Maybe show Assets / Vault values for all users but Grey out the downloadable Assets for the other users.

I think 1 is probably easier to do, but curious to know your thoughts on this...

**Comment by NathanaelA** [comment]
See #18, I believe this will solve your issue since you can have multiple data folders, one for each user.
