### ISSUE TITLE
[Bug] Unreal Engine download goes to Vault Cache instead of Base Unreal Engine directory

### ISSUE THREAD

**Issue by randomperson189** [master-technology/AssetManagerStudio#20]
When I download Unreal Engine via AMS, it seems to download it to where my Vault Cache is, it should actually download to your Base Unreal Path like how Epic Games Launcher does it. The downloaded engine folder is also in a folder called data for some reason when it doesnt when downloaded via EGL. This could possibly cause issues of not fixed

**Comment by NathanaelA** [comment]
This is by design at this moment, all items from the Epic CDN are downloaded to the Vault directory.     Then in the engines case it is "moved" rather than "copied" to the destination.    I might in the future add additional logic to AMS to allow it to  directly download the engines to the destination folder, but at this point it keeps the code a lot simpler since virtually all downloads from epic are treated identically.
