### ISSUE TITLE
Update broke asset retrieval

### ISSUE THREAD

**Issue by WeirdScienceX** [master-technology/AssetManagerStudio#30]
Version 0.0.24, login button is grayed out. 

`INFO:   [ Renderer ] Gui active at 211.30000000004657

INFO:   Window is Hidden

INFO:   [ Renderer ] Gui Finished at 268

DEBUG:  Fixing it... for https://www.epicgames.com/id/login

INFO:   Login Window Loaded, Cookies found: 0

INFO:   [ Worker ] [Vault Scanner] Scanning for vault items in C:\ProgramData\Epic\EpicGamesLauncher\VaultCache\

INFO:   Login Completed via redirect json

ERROR:  Unable to get Session ID [object Object]

INFO:   [ Assets ] Last Update 60996 seconds ago

INFO:   [ Assets ] Skipping Update...

INFO:   [ Startup ] Done with updateAsset at Gui startup...

DEBUG:  [Security] Will Navigate https://epicgames.com/account/personal

DEBUG:  No Asset Manager Studio update needed.

DEBUG:  Fixing it... for https://www.epicgames.com/account/personal

ERROR:  getAssets: 401

ERROR:  [ Assets] Failed to retrieve asset data from server, you might need to login?

INFO:   [ Startup ] Done with updateAsset at Gui startup...`

**Comment by NathanaelA** [comment]
Yeah, I've been working on this issue for a couple days working on trying to fix the login flow since Epic changed it again.   It is a LOT more picky at this point. 

 Since someone else has finally hit it, I will try and release a version tonight with a method to externally login and grab the authcode like others launchers use until I can figure out how to make the normal login flow work again...

**Comment by NathanaelA** [comment]
This should be fixed in the new 0.0.25 release...
