### ISSUE TITLE
why no copy function for the information window? (And more)

### ISSUE THREAD

**Issue by FritzHugo3** [master-technology/AssetManagerStudio#53]
Nice that you can read the descriptions better, Description, Technicals, Images, Q&A - WHY!!!! Can't you highlight and copy anything? Simply not understandable. I'm building an Excel database and you have to rewrite everything that is already there as text because you simply can't mark/copy - just nonsensical!

A second thing, WHY, is not exactly the same information displayed for information packages that have already been downloaded. You are forced to go to your huge library instead of the already downloaded vault for the same pack information. 

And why is there only one download at a time? My internet is only used 20% of the time. Parallel downloads would make a lot of sense. Also, the Asset Manager Studio locks the folder names as long as it is open, even if nothing is being written/read. 

There is still a lot to improve but still much better than this completely crap Epic Launcher, which is completely unusable. Please keep working on this manager, it has clear advantages, but there is still room for improvement.

Thank a lot.

Translated with DeepL.com (free version)

**Comment by NathanaelA** [comment]
>Nice that you can read the descriptions better, Description, Technicals, Images, Q&A - WHY!!!! Can't you highlight and copy anything? Simply not understandable. I'm building an Excel database and you have to rewrite everything that is already there as text because you simply can't mark/copy - just nonsensical!

The reason why is because I REALLY, REALLY hate when I click things and it starts selecting things or dragging them. :wink:         However, rather than use the GUI, have you tried the Command line?    You can export ALL sorts of cool info all to files, if there is more info you need than what I offer let me know and I'll add it.

![image](https://github.com/user-attachments/assets/fd17763f-aa49-4ee7-b37b-57506692ac25)



> A second thing, WHY, is not exactly the same information displayed for information packages that have already been downloaded. You are forced to go to your huge library instead of the already downloaded vault for the same pack information.

This is not a bad idea, I could easily display it...   Would you mind creating a feature request for this feature?


> And why is there only one download at a time? My internet is only used 20% of the time. Parallel downloads would make a lot of sense. 

Because I haven't cleaned up that part of the code much, this is still a very early beta and it is still being worked on when I have free time.   (Right now spending a lot of time looking for a job, got laid off a month ago, so that means AMS is fairly low on my priority until I get a job, or more contract work)


Eventually I would like to have a full download management system,  you should have seen it in the first few versions,  it only allowed one download, certain things weren't supported or done in the background and NO queuing of downloads...  :wink:


> Also, the Asset Manager Studio locks the folder names as long as it is open, even if nothing is being written/read.

I haven't seen this, what folders exactly are locked and when?


> There is still a lot to improve but still much better than this completely crap Epic Launcher, which is completely unusable. Please keep working on this manager, it has clear advantages, but there is still room for improvement.

Still working on it, trying to get a new version out with actual FAB support, have already done all the API digging and have notes, just have to finish coding everything.

**Comment by FritzHugo3** [comment]
![grafik](https://github.com/user-attachments/assets/8c159388-f0da-44ed-bc18-f35297a16f1d)

Thank you very much for answering me and so quickly. That is rare. 

Nice to hear that you still plan to actively work on it, how about directories to be able to move things more individually into your own categories, or to provide your own tags and the like? (just an idea)

I really can't understand why you actively don't want to be able to mark and copy the information on the screen, as this window is then completely pointless. People then have to go back to the FAB website and laboriously click their way through. I have to enter version numbers, descriptions, author, license type, links, features etc. all in different Excel fields. It makes no sense to do anything via a DOS console. 
These information pages in the program are simply not usable if you can't do anything with them. Then they could be left out completely. Nothing has to be marked automatically, just a cursor with which the user can mark the text manually, as is possible on any website in the world.

The thing with the locked folders is that if I have downloaded a package, I can only rename the folder after I have closed your program, it retains the sole access rights to it. It is probably forgotten when the download is finished that it can be unlocked again. (I suspect)

I don't quite understand why I should write the same text again with the suggestion in a new chat? I probably misunderstood something or something got lost in the automatic translation. 

Another idea, the downloaded folders are not called what the asset packages are called, just an initial word and then a strange combination of numbers/letters - how about your program renaming the downloaded folder automatically with the title of the asset package (which is in the jason file). I have great difficulty renaming the right folders the next morning because you almost have to guess what is what. 

How about really making your program a full-fledged manager and a real help and game changer for everyone who works with assets. With a function to also display local assets, library possibility... There is so much need and hardly any good software for this area. What Epic and FAB's offer is really sad. And then you sell your program for little money, maybe 5$ and make sure it becomes a mass need. That everyone who uses FAB stuff wants to have your tool (that's why it mustn't cost too much, the masses will do it in the end, so that you can live from it). I have 30,000 assets and absolutely no great way to have an overview of every single mesh, no custom sorting and so on. There are so many improvement possibilities for working methods. And huge potential. 

For example, a 3D view for the locally downloaded things - I can think of so many things that are missing from good software solutions. If you can do something like that, you can get really rich with it.  There is simply no such thing!

I hope you will soon find a new, nice employer where you can live out your dreams and work creatively. 
Translated with DeepL.com (free version)

Have a verry nice weekend

**Comment by FritzHugo3** [comment]
I found something - this here: https://www.fab.com/listings/9bdca455-6c4a-4e9f-b1db-e0dbcf536e28
Are in my epic Launcher in my library but for your program it is invisible, not found. All other environments are fine - no idea why this not work.

**Comment by NathanaelA** [comment]
> I found something - this here: https://www.fab.com/listings/9bdca455-6c4a-4e9f-b1db-e0dbcf536e28 Are in my epic Launcher in my library but for your program it is invisible, not found. All other environments are fine - no idea why this not work.

That is because FAB support is being worked on, anything you purchased on FAB doesn't show up yet.   The next version should support FAB.   Just haven't had time to finish coding up all the new API's.

**Comment by NathanaelA** [comment]
> Nice to hear that you still plan to actively work on it, how about directories to be able to move things more individually into your own categories, or to provide your own tags and the like? (just an idea)

Custom tags and categories are planned.  The ultimate goal of the app is to make it be able to easily manage all your assets including other non-epic assets (i.e. from other sites  :grinning: )

As for Directories, you can create whatever structure you want, the program supports unlimited number of vault directories.   Mine machine I have a couple vault directories in different drives for some organization.    HOWEVER, downloading currently will always put them in your last vault directory.

> I really can't understand why you actively don't want to be able to mark and copy the information on the screen, as this window is then completely pointless. People then have to go back to the FAB website and laboriously click their way through. I have to enter version numbers, descriptions, author, license type, links, features etc. all in different Excel fields. It makes no sense to do anything via a DOS console.

- Because you can actually get way more info from the command line, and you can do it programatically.    
- Normally you don't need to copy anything out of the app, you are viewing it to see if you want to use it.  :wink:
- However I'll add a mode you can enable selecting the text in the detail panels...

  
> The thing with the locked folders is that if I have downloaded a package, I can only rename the folder after I have closed your program, it retains the sole access rights to it. It is probably forgotten when the download is finished that it can be unlocked again. (I suspect)

  Strange, I'll look at the code, but I'm pretty sure I close all files in that directory which should be what would lock it...   


> I don't quite understand why I should write the same text again with the suggestion in a new chat? I probably misunderstood something or something got lost in the automatic translation.

It is easier to track each feature or problem as a separate github issue.  Having a lot of issues in the same github issue, means it is very likely I will forget something at a later point.   So when I ask for you to open a new issue, feel free to copy & paste the relevant info into a new issue so it stands alone.


> How about really making your program a full-fledged manager and a real help and game changer for everyone who works with assets. With a function to also display local assets, library possibility... There is so much need and hardly any good software for this area. What Epic and FAB's offer is really sad. And then you sell your program for little money, maybe 5$ and make sure it becomes a mass need. That everyone who uses FAB stuff wants to have your tool (that's why it mustn't cost too much, the masses will do it in the end, so that you can live from it). I have 30,000 assets and absolutely no great way to have an overview of every single mesh, no custom sorting and so on. There are so many improvement possibilities for working methods. And huge potential.

Actually this is the ultimate goal, I started it with Unreal Marketplace & Standalone Unreal assets (i.e. Unreal assets you have manually d/l from anywhere else -- just drop them in a folder that AMS can catalog and it should pick them up).    I'm currently adding Fab support in the next version.     Down the road other sites, then eventually standalone assets (like individual wav, obj, fbx, png, etc).

> For example, a 3D view for the locally downloaded things - I can think of so many things that are missing from good software solutions. If you can do something like that, you can get really rich with it. There is simply no such thing!

Actually that is on the drawing board already.   I have a LOT of feature ideas, just very little "spare" time.

**Comment by FritzHugo3** [comment]
![grafik](https://github.com/user-attachments/assets/c52b40b5-2f32-4724-8625-1d9619d2b03b)

I sent some downloads into the pipeline for tonight, but unfortunately many of them were canceled and it won't continue. Since there are no names on them, I now have to search the whole library to see what's there and what's not. If the names were there, it would be much easier.

A button to restart the download wouldn't be a bad idea either - if it continued where it left off, that would be great, but even if it just restarted, it would save a lot of work. In Germany, many people have problems with the Internet in terms of stability. 



   "The ultimate goal of the app is to make it be able to easily manage all your assets including other non-epic assets (i.e. from 
   other sites 😀 )"
   That would be a dream - people spend mony for a good tool like that. 

What I've been doing for two months, downloading environments, making thumbnails of everything (because the real assets would take up too much memory and I couldn't see them in Explorer).

I want to build a database that is local to me, has all the images of the 3d objects and I can assign tags myself and then simply search my 30,000-50,000 objects by keyword. Chair, table, vase and then I see 100 chairs or tables or vases in the browser (or somewhere else) without loading time, search for the one I want for my project, see in which package it is hidden, download this package and then extract the asset for Blöender or any other program. 

And there is NO decent, cool software for that - if you were planning something like that, EVERYONE would want it. Epic/FAB's/Brixel, none of them are easy to use!



   "Because you can actually get way more info from the command line, and you can do it programatically.
    Normally you don't need to copy anything out of the app, you are viewing it to see if you want to use it. 😉"
    
How many users know that it exists, how many people know how to use it, how many people actually use it. I honestly don't think it's that many, Dos consoles were used in 1985 or so. It may be different for Mac and Linux users, but I don't know anyone who does anything in Windows via an input window. 

   "However I'll add a mode you can enable selecting the text in the detail panels..."
This would be helping so much! Would be very nice! I say much time thank you. 


   "It is easier to track each feature or problem as a separate github issue. Having a lot of issues in the same github issue, means 
   it is very likely I will forget something at a later point. So when I ask for you to open a new issue, feel free to copy & paste the 
   relevant info into a new issue so it stands alone."
Ah ok, than I will do it to night and open some new chats with only one suggestion. (It feels for me a little bit spammy, private I like more one but no problem, if you prefer this, I can do it)


Have a verry nice Weekend

**Comment by NathanaelA** [comment]
> What I've been doing for two months, downloading environments, making thumbnails of everything (because the real assets would take up too much memory and I couldn't see them in Explorer).

Yikes, that is a lot of work...  :wink:


> I want to build a database that is local to me, has all the images of the 3d objects and I can assign tags myself and then simply search my 30,000-50,000 objects by keyword. Chair, table, vase and then I see 100 chairs or tables or vases in the browser (or somewhere else) without loading time, search for the one I want for my project, see in which package it is hidden, download this package and then extract the asset for Blöender or any other program.

Yep, this is the ultimate place I want to be with AMS in the not so distant future.   I actually want to have information for all the sub-assets in an epic asset.  So if you download an environment, AMS would be able to show you all the separate props that are included with it to allow you to easily import (& d/l) a SINGLE prop from the environment asset.   I likewise have a massive library that is totally un-organized and it drives me nuts -- which is part of my goals to be able to actually organize it in some fashion and part of that is knowing what is in each asset.     


> I sent some downloads into the pipeline for tonight, but unfortunately many of them were canceled and it won't continue. Since there are no names on them, I now have to search the whole library to see what's there and what's not. If the names were there, it would be much easier.

Hmm, I thought I was showing the names that failed, but I'll make sure to add them to the next version...  


> A button to restart the download wouldn't be a bad idea either - if it continued where it left off, that would be great, but even if it just restarted, it would save a lot of work. In Germany, many people have problems with the Internet in terms of stability.

I actually have a placeholder menu option commented out in the code to "Resume", just have to find the time to implement the code.     

I should also mention AMS does already do multiple d/l's at a time, but when you have fast bandwidth the CAP appears  to low.    I need to figure out a good method to dynamically cap it, rather than hard code it.     But if you want to change the CAP on the number of d/l's there are you can see the wiki here: https://github.com/master-technology/AssetManagerStudio/wiki/Notes-Hidden-Settings.    

Please note this is NOT the number of different asset packs that can d/l but the number of separate items in an asset pack as each epic asset is made up of typically a lot of files, the current version is capped at 4 items at a time, I think I'll probably expose the setting in the next version and default it to 16 as EVERYONE is telling me it doesn't use much d/l bandwidth.  :grin:

**Comment by FritzHugo3** [comment]
I swear, thousands of people would be spend 5$/5€for this
"So if you download an environment, AMS would be able to show you all the separate props that are included with it to allow you to easily import (& d/l) a SINGLE prop from the environment asset."

And than individual Tags for User for this  - this would be what all people need!

not more 2 month stupid work - You load an environmant and geht single 200 models exported as a thumbnail or something like that - this would be soooo great. 

"Hmm, I thought I was showing the names that failed"
Not work for me, it still dont download without an error message - the program stops download without anything. (I cant say exackt whats happen, because I was sleeping, maybe internet problems in this time. 

Another question, since the problem, I am also missing 20 GB of memory on C: and I can't find where the bodies are hidden. Does the program use any temporary files? 

The problem with bandwidth is also that Epic does not offer zip. a single large file is much more stable than 500 single small files ^^. It fluctuates like crazy. But of course your program can't help that. I barely get over 20Mbit here, out of 100Mbit that would be possible. actually not fast in worldwide comparison. Sometimes I had to wait an hour for a packet.
(In the meantime I think I have downloaded them all in three days) 


In any case, stick to your plans for this software. Maybe you'll middle timed no longer need an employer and just do the software for a living. Even if the software can do all this at some point, it will of course be a question of getting enough publicity, but word will get around among professionals when there is something that can do weeks and months of work at the touch of a button. 

Even for private people, a library of their pictures could become interesting. There is so much potential in my eyes. and the number of images created by AI's is so huge. in one night I make 1,000 new images locally on my computer, only I stopped because I can't manage them.

**Comment by NathanaelA** [comment]
>  And than individual Tags for User for this - this would be what all people need!

Yes everything would be tagged individually.  Once this feature is completed...  Still working out all the logistics and UI.


>   I am also missing 20 GB of memory....  Does the program use any temporary files?

The only temporary files are the browser cache, you can find the directories listed here: https://github.com/master-technology/AssetManagerStudio/wiki/Notes-Windows-Os  (I assume you are using windows since you mentioned windows above).       My cache/db directory is currently using 300mb, most of that is mainly from the over images for all the assets I own as they are cached by the browser so that when you startup it doesn't have to re-download them to show them again.   Unfortunately images can be large, but I do have a project to auto-process images to a thumbnail size in the future to save space for the asset images, but it is a very low priority on my todo list...

Not sure if you have seen it, but the vault view allows you to sort assets by size and gives you the total amount of disk space used by all your asset vaults...  

**AND** 

you can enable in the settings the ability to auto DELETE any "pointless" asset stuff that doesn't apply to your platform.   So when you download say a plugin, if it has included any Mac or Linux stuff, AMS can auto-delete the Mac/Linux stuff from the asset after it finishes the download (& will do so also during scanning of assets).   I freed up a massive amount of disk space the first time I ran it against my asset library.   :grinning:

Finally if you still can't find your missing space, you can use WinDirStat to find out what is using space on a drive, easily, that is my go to app on Windows.

**Comment by FritzHugo3** [comment]
I use TreeSizeFree.
Mhh strange, then your tool is apparently not the reason.

I have a completely different partition for the assets - I suspected temporary files on C: because the downloads were canceled. But apparently there is no such thing. 

Epic/Unreal itself is cluttering up everything under program files + local anyway, but this time it was something else. Well, I'll find out later. Maybe shader or something else ^^. I'll find out one day.

If only I had the time and nerves, I would have to completely reinstall my Windows, of the 500GB SSD, 250GB are certainly just data garbage. But when I think of the weeks of effort until everything is installed and set up again ^^. Anyway, I digress LUL.

**Comment by NathanaelA** [comment]
I just released v0.0.26 which should fix and/or add many of the issues you brought up (including ability to select/copy!).    If you feel like I missed something please open separate bug/feature reports so that I don't drop them.  ;-)

**Comment by FritzHugo3** [comment]
Oh, thx a lot. 

(And I found my GB's here: AppData\Local\UnrealEngine\Common\DerivedDataCache\Content
55GB complet waste garbage)
